{{- define "common.istio-gateway-virtualservice.tpl" -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
{{ template "common.metadata" .}}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    {{- if eq .Values.ingress.proto "https" }}
    tls:
      httpsRedirect: true
    {{- end}}
    hosts:
    - "{{ .Values.ingress.host }}.{{ .Values.ingress.domain }}"
  {{- if eq .Values.ingress.proto "https" }}
  - hosts:
    - "{{ .Values.ingress.host }}.{{ .Values.ingress.domain }}"
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
    {{- end}}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
{{ template "common.metadata" .}}
spec:
  hosts:
  "{{ .Values.ingress.host }}.{{ .Values.ingress.domain }}"
  gateways:
  - {{ template "common.fullname" . }}


{{- end -}}
